# -*- coding: utf-8 -*-
"""VisionExtract_Isolation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZM7a7NCh79vHWjMj7LmZem6iLXQ522mW

# Milestone 1:Data Preprocessing and validation
"""

!pip install kagglehub

import kagglehub

# Download latest version
path = kagglehub.dataset_download("awsaf49/coco-2017-dataset")

print("Path to dataset files:", path)

import os

for root, dirs, files in os.walk(path):
    print("Folder:", root)
    print("Subfolders:", dirs)
    print("Files:", files[:5])  # print first 5 only
    print("-" * 50)

!pip install pycocotools
!pip install opencv-python
!pip install matplotlib

from pycocotools.coco import COCO
import matplotlib.pyplot as plt
import cv2
import numpy as np
import random
import os

ann_file = os.path.join(path, "coco2017", "annotations", "instances_train2017.json")
coco = COCO(ann_file)

# Get all image IDs
img_ids = coco.getImgIds()

# Select random image
img_id = random.choice(img_ids)

# Load image info
img_info = coco.loadImgs(img_id)[0]
img_path = os.path.join(path, "coco2017", "train2017", img_info['file_name'])

# Read image
image = cv2.imread(img_path)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Get annotation IDs for this image
ann_ids = coco.getAnnIds(imgIds=img_id)
anns = coco.loadAnns(ann_ids)

# Create empty mask
mask = np.zeros((img_info['height'], img_info['width']))

# Merge all instance masks into single binary mask
for ann in anns:
    mask += coco.annToMask(ann)

# Convert to binary (0 or 1)
mask = np.clip(mask, 0, 1)

# Show image and mask
plt.figure(figsize=(12,6))

plt.subplot(1,2,1)
plt.title("Original Image")
plt.imshow(image)
plt.axis("off")

plt.subplot(1,2,2)
plt.title("Combined Binary Mask")
plt.imshow(mask, cmap='gray')
plt.axis("off")

plt.show()

# Expand mask to 3 channels
mask_3ch = np.stack([mask]*3, axis=-1)

# Apply mask
isolated = image * mask_3ch

plt.figure(figsize=(6,6))
plt.title("Subject Isolated (Background Black)")
plt.imshow(isolated.astype(np.uint8))
plt.axis("off")
plt.show()

!pip install pycocotools
!pip install albumentations
!pip install segmentation-models-pytorch

import os
import cv2
import torch
import numpy as np
from torch.utils.data import Dataset
from pycocotools.coco import COCO
import albumentations as A
from albumentations.pytorch import ToTensorV2

def get_train_transforms():
    return A.Compose([
        A.Resize(256, 256),
        A.HorizontalFlip(p=0.5),
        A.VerticalFlip(p=0.2),
        A.RandomBrightnessContrast(p=0.3),
        A.Normalize(),
        ToTensorV2()
    ])

def get_val_transforms():
    return A.Compose([
        A.Resize(256, 256),
        A.Normalize(),
        ToTensorV2()
    ])

from torch.utils.data import Dataset
from pycocotools.coco import COCO
import cv2
import numpy as np
import os

class COCOSegmentationDataset(Dataset):
    def __init__(self, images_dir, annotation_file, transforms=None):
        self.images_dir = images_dir
        self.coco = COCO(annotation_file)
        self.image_ids = self.coco.getImgIds()
        self.transforms = transforms

    def __len__(self):
        return len(self.image_ids)

    def __getitem__(self, idx):

        img_id = self.image_ids[idx]
        img_info = self.coco.loadImgs(img_id)[0]

        img_path = os.path.join(self.images_dir, img_info['file_name'])

        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        mask = np.zeros((img_info['height'], img_info['width']))

        ann_ids = self.coco.getAnnIds(imgIds=img_id)
        anns = self.coco.loadAnns(ann_ids)

        for ann in anns:
            mask += self.coco.annToMask(ann)

        mask = np.clip(mask, 0, 1).astype(np.float32)

        if self.transforms:
            augmented = self.transforms(image=image, mask=mask)
            image = augmented["image"]
            mask = augmented["mask"]

        mask = mask.unsqueeze(0)

        return image, mask

class COCOSegmentationDataset(Dataset):
    def __init__(self, images_dir, annotation_file, transforms=None):
        self.images_dir = images_dir
        self.coco = COCO(annotation_file)
        self.image_ids = self.coco.getImgIds()
        self.transforms = transforms

    def __len__(self):
        return len(self.image_ids)

    def __getitem__(self, idx):
        img_id = self.image_ids[idx]
        img_info = self.coco.loadImgs(img_id)[0]
        img_path = os.path.join(self.images_dir, img_info['file_name'])

        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        # Create empty mask
        mask = np.zeros((img_info['height'], img_info['width']))

        ann_ids = self.coco.getAnnIds(imgIds=img_id)
        anns = self.coco.loadAnns(ann_ids)

        for ann in anns:
            mask += self.coco.annToMask(ann)

        mask = np.clip(mask, 0, 1).astype(np.float32)

        if self.transforms:
            augmented = self.transforms(image=image, mask=mask)
            image = augmented["image"]
            mask = augmented["mask"]

        # Add channel dimension to mask
        mask = mask.unsqueeze(0)

        return image, mask

import os
from torch.utils.data import DataLoader

path = "/kaggle/input/coco-2017-dataset"

train_images = os.path.join(path, "coco2017", "train2017")
val_images = os.path.join(path, "coco2017", "val2017")

train_ann = os.path.join(path, "coco2017", "annotations", "instances_train2017.json")
val_ann = os.path.join(path, "coco2017", "annotations", "instances_val2017.json")

train_dataset = COCOSegmentationDataset(
    train_images,
    train_ann,
    transforms=get_train_transforms()
)

val_dataset = COCOSegmentationDataset(
    val_images,
    val_ann,
    transforms=get_val_transforms()
)

train_loader = DataLoader(
    train_dataset,
    batch_size=4,
    shuffle=True,
    num_workers=2
)

val_loader = DataLoader(
    val_dataset,
    batch_size=4,
    shuffle=False,
    num_workers=2
)

import matplotlib.pyplot as plt

image, mask = train_dataset[10]

image_np = image.permute(1,2,0).numpy()
mask_np = mask.squeeze().numpy()

plt.figure(figsize=(12,5))

plt.subplot(1,3,1)
plt.title("Image")
plt.imshow(image_np)
plt.axis("off")

plt.subplot(1,3,2)
plt.title("Mask")
plt.imshow(mask_np, cmap='gray')
plt.axis("off")

plt.subplot(1,3,3)
plt.title("Overlay")
plt.imshow(image_np)
plt.imshow(mask_np, alpha=0.5, cmap='jet')
plt.axis("off")

plt.show()

"""## Milestone 2: Week 3 - Initial Model Training

- Implement U-Net.
- Train on processed data, monitor metrics.
- Visualize early predictions.
"""

# Week 3: Model Setup
import torch.nn as nn
from segmentation_models_pytorch import Unet
from segmentation_models_pytorch.losses import DiceLoss
from torchmetrics import JaccardIndex
import torch.optim as optim
from tqdm import tqdm

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Using device:", device)

model = Unet(encoder_name='resnet34', encoder_weights='imagenet', in_channels=3, classes=1, activation='sigmoid')
model.to(device)

criterion = nn.BCEWithLogitsLoss()
dice_loss = DiceLoss(mode='binary')
optimizer = optim.Adam(model.parameters(), lr=1e-4)
iou_metric = JaccardIndex(task='binary').to(device)

# Week 3: Training Loop (5 epochs with progress)
num_epochs = 5
train_losses, val_ious = [], []

for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    train_pbar = tqdm(train_loader, desc=f"Epoch {epoch+1} Train", total=len(train_loader))
    for imgs, masks in train_pbar:
        imgs, masks = imgs.to(device), masks.float().to(device)
        optimizer.zero_grad()
        preds = model(imgs)
        loss = criterion(preds.squeeze(1), masks.squeeze(1)) + dice_loss(preds, masks)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
        train_pbar.set_postfix(loss=loss.item())
    train_losses.append(running_loss / len(train_loader))

    model.eval()
    iou_score = 0.0
    val_pbar = tqdm(val_loader, desc=f"Epoch {epoch+1} Val", total=len(val_loader))
    with torch.no_grad():
        for imgs, masks in val_pbar:
            imgs, masks = imgs.to(device), masks.float().to(device)
            preds = model(imgs)
            iou = iou_metric(preds.squeeze(1) > 0.5, masks.squeeze(1)).item()
            iou_score += iou
            val_pbar.set_postfix(iou=iou)
    val_ious.append(iou_score / len(val_loader))

    print(f"Epoch {epoch+1}/{num_epochs} - Train Loss: {train_losses[-1]:.4f}, Val IoU: {val_ious[-1]:.4f}")

# Plot
plt.figure(figsize=(10, 4))
plt.subplot(1,2,1); plt.plot(train_losses); plt.title('Train Loss'); plt.xlabel('Epoch')
plt.subplot(1,2,2); plt.plot(val_ious); plt.title('Val IoU'); plt.xlabel('Epoch')
plt.tight_layout()
plt.show()  # Screenshot: Training curves

# Week 3: Visualize Early Predictions
model.eval()
with torch.no_grad():
    imgs, masks = next(iter(val_loader))
    imgs, masks = imgs.to(device), masks.to(device)
    preds = model(imgs)
    pred_masks = (preds > 0.5).float().squeeze(1)

img_vis = denorm(imgs[0]).permute(1,2,0).cpu().numpy().clip(0,1)
gt_mask = masks[0].squeeze().cpu().numpy()
pred_mask = pred_masks[0].cpu().numpy()

isolated = img_vis.copy()
isolated[pred_mask == 0] = 0

fig, axs = plt.subplots(1, 4, figsize=(16, 4))
axs[0].imshow(img_vis); axs[0].set_title("Input Image")
axs[1].imshow(gt_mask, cmap='gray'); axs[1].set_title("GT Mask")
axs[2].imshow(pred_mask, cmap='gray'); axs[2].set_title("Pred Mask")
axs[3].imshow(isolated); axs[3].set_title("Isolated Subject")
for ax in axs: ax.axis('off')
plt.tight_layout()
plt.show()  # Screenshot: Early predictions

"""## Milestone 2: Week 4 - Predictions and Fine-Tuning

- Val predictions vs. GT.
- Metrics (IoU/Dice).
- Fine-tune: Add rotation aug, lower LR, retrain 3 epochs.
"""

# Week 4: Val Predictions & Metrics
import torchmetrics.functional as F
import random
import numpy as np



model.eval()
all_ious, all_dices = [], []
with torch.no_grad():
    for imgs, masks in val_loader:
        imgs, masks = imgs.to(device), masks.float().to(device)
        preds = model(imgs)
        pred_bins = (preds > 0.5).float().squeeze(1)
        all_ious.append(iou_metric(pred_bins, masks.squeeze(1)).item())
        # Calculate dice using functional API (F1-score is equivalent to Dice for binary)
        all_dices.append(F.f1_score(pred_bins.long(), masks.squeeze(1).long(), task='binary').item())

mean_iou = np.mean(all_ious)
mean_dice = np.mean(all_dices)
print(f"Val Mean IoU: {mean_iou:.4f}, Dice: {mean_dice:.4f}")

# 3 Sample Outputs
samples = [val_ds[i] for i in random.sample(range(len(val_ds)), 3)]
fig, axs = plt.subplots(3, 4, figsize=(16, 12))
for j, (img, gt) in enumerate(samples):
    img_tensor = denorm(img.unsqueeze(0).to(device)).squeeze().permute(1,2,0).cpu().numpy().clip(0,1)

    with torch.no_grad():
        pred = model(img.unsqueeze(0).to(device))
    pred_mask = (pred > 0.5).float().squeeze().cpu().numpy()

    isolated = img_tensor.copy()
    isolated[pred_mask == 0] = 0

    axs[j,0].imshow(img_tensor); axs[j,0].set_title("Input")
    axs[j,1].imshow(gt.squeeze().numpy(), cmap='gray'); axs[j,1].set_title("GT Mask")
    axs[j,2].imshow(pred_mask, cmap='gray'); axs[j,2].set_title("Pred Mask")
    axs[j,3].imshow(isolated); axs[j,3].set_title("Isolated")
    for col in range(4): axs[j,col].axis('off')
plt.tight_layout()
plt.show()

# Week 4: Fine-Tuning (Add rotation, lower LR)
train_transform = A.Compose([
    A.Resize(256, 256),
    A.HorizontalFlip(p=0.5),
    A.Rotate(limit=15, p=0.3),
    A.RandomBrightnessContrast(p=0.2),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2()
])
train_ds = COCOSubjectDataset(coco, train_img_dir, train_ids, train_transform)
train_loader = DataLoader(train_ds, batch_size=8, shuffle=True, num_workers=0, pin_memory=True)

optimizer = optim.Adam(model.parameters(), lr=1e-5)

# Retrain 3 epochs
fine_epochs = 3
for epoch in range(fine_epochs):
    model.train()
    running_loss = 0.0
    train_pbar = tqdm(train_loader, desc=f"Fine Epoch {epoch+1} Train", total=len(train_loader))
    for imgs, masks in train_pbar:
        imgs, masks = imgs.to(device), masks.float().to(device)
        optimizer.zero_grad()
        preds = model(imgs)
        loss = criterion(preds.squeeze(1), masks.squeeze(1)) + dice_loss(preds, masks)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
        train_pbar.set_postfix(loss=loss.item())
    print(f"Fine Epoch {epoch+1} - Loss: {running_loss / len(train_loader):.4f}")

from google.colab import files
files.upload()

import os

os.makedirs("/root/.kaggle", exist_ok=True)
!mv kaggle.json /root/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json

!kaggle datasets download -d awsaf49/coco-2017-dataset

!unzip -q coco-2017-dataset.zip

train_img_dir = "train2017"
train_ann_file = "annotations/instances_train2017.json"

import os
from pycocotools.coco import COCO

# auto-find paths
base = "/kaggle/input"
train_ann_file, train_img_dir = None, None

for root, dirs, files in os.walk(base):
    if "instances_train2017.json" in files:
        train_ann_file = os.path.join(root, "instances_train2017.json")
    if root.endswith("train2017"):
        train_img_dir = root

# correct dataset call (FIXED)
train_ds = COCOSubjectDataset(
    annotation_file=train_ann_file,
    img_dir=train_img_dir,
    transform=None
)

print("Dataset loaded successfully")

train_ann_file = "/kaggle/input/coco-2017-dataset/coco2017/annotations/instances_train2017.json"
train_img_dir = "/kaggle/input/coco-2017-dataset/coco2017/train2017"

from pycocotools.coco import COCO

coco = COCO(train_ann_file)

train_ds = COCOSubjectDataset(
    annotation_file=train_ann_file,
    img_dir=train_img_dir,
    transform=None
)

print("Working successfully")

import os
from pycocotools.coco import COCO

data_dir="/content/coco2017"
ann_file=os.path.join(data_dir, "annotations/instances_train2017.json")
coco=COCO(ann_file)

# Install albumentations if not already installed
!pip install -q albumentations

import os
import cv2
import torch
import numpy as np # Import numpy for mask operations
from torch.utils.data import Dataset, DataLoader
from pycocotools.coco import COCO
import albumentations as A
from albumentations.pytorch import ToTensorV2

train_ann_file = "/content/coco2017/annotations/instances_train2017.json"
train_img_dir = "/content/coco2017/train2017"

coco2017 = COCO(train_ann_file)
train_ids = list(coco2017.imgs.keys())

class COCOSubjectDataset(Dataset):
    def __init__(self, coco, img_dir, img_ids, transform=None):
        self.coco = coco
        self.img_dir = img_dir
        self.image_ids = img_ids
        self.transform = transform

    def __len__(self):
        return len(self.image_ids)

    def __getitem__(self, idx):
        img_id = self.image_ids[idx]
        img_info = self.coco.loadImgs(img_id)[0]
        img_path = os.path.join(self.img_dir, img_info['file_name'])

        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        ann_ids = self.coco.getAnnIds(imgIds=img_id, iscrowd=None) # Get all annotations
        anns = self.coco.loadAnns(ann_ids)

        # Create an empty mask for the image
        height, width = img_info['height'], img_info['width']
        mask = np.zeros((height, width), dtype=np.uint8)

        # Iterate over annotations and combine masks into a single binary mask
        for ann in anns:
            current_mask = self.coco.annToMask(ann)
            mask = np.maximum(mask, current_mask) # Combine masks by taking the maximum

        if self.transform:
            # Albumentations expects mask for segmentation transforms
            transformed = self.transform(
                image=image,
                mask=mask
            )
            image = transformed["image"]
            mask = transformed["mask"]

        # Ensure mask is a float tensor and has a channel dimension (1, H, W) for PyTorch
        if isinstance(mask, np.ndarray):
            mask = torch.from_numpy(mask).float().unsqueeze(0)
        elif isinstance(mask, torch.Tensor) and mask.dim() == 2:
            mask = mask.unsqueeze(0)

        return image, mask # Return image and the combined segmentation mask

train_transform_refined = A.Compose([
    A.Resize(256, 256),
    A.HorizontalFlip(p=0.5),
    A.ElasticTransform(p=0.2),
    A.GridDistortion(p=0.2),
    A.RandomBrightnessContrast(p=0.2),
    A.Normalize(mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225]),
    ToTensorV2()
]) # Removed bbox_params as we are not returning bboxes

train_ds = COCOSubjectDataset(
    coco=coco2017,
    img_dir=train_img_dir,
    img_ids=train_ids,
    transform=train_transform_refined
)

train_loader = DataLoader(
    train_ds,
    batch_size=8,
    shuffle=True,
    num_workers=0,
    pin_memory=True
)

print("Training pipeline ready")
print("Total samples:", len(train_ds))

import torch
import torch.nn as nn
import torch.optim as optim
from segmentation_models_pytorch import Linknet
from segmentation_models_pytorch.losses import DiceLoss
from torchmetrics import JaccardIndex
from tqdm.notebook import tqdm
from torch.utils.data import DataLoader

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Limit dataset size (FIX)
train_ids = list(coco.imgs.keys())[:100]

# Recreate dataset with limited samples (IMPORTANT)
train_ds = COCOSubjectDataset(
    coco=coco,
    img_dir=train_img_dir,
    img_ids=train_ids,
    transform=train_transform_refined
)

# Model (FIX: remove sigmoid)
model_linknet = Linknet(
    encoder_name='resnet34',
    encoder_weights='imagenet',
    in_channels=3,
    classes=1,
    activation=None
)
model_linknet.to(device)

# Loss, optimizer, metric
criterion = nn.BCEWithLogitsLoss()
dice_loss = DiceLoss(mode='binary')
optimizer = optim.Adam(model_linknet.parameters(), lr=1e-4)
iou_metric = JaccardIndex(task='binary').to(device)

# Collate function
def custom_collate_fn(batch):
    images = [item[0] for item in batch]
    masks = [item[1] for item in batch]
    return torch.stack(images, 0), torch.stack(masks, 0)

# DataLoader (FIXED)
train_loader = DataLoader(
    train_ds,
    batch_size=4,
    shuffle=True,
    num_workers=2,
    pin_memory=False,
    collate_fn=custom_collate_fn
)

# Training loop
num_epochs = 5
linknet_train_losses = []

for epoch in range(num_epochs):
    model_linknet.train()
    running_loss = 0.0

    train_pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}", total=len(train_loader))

    for imgs, masks in train_pbar:
        if len(masks.shape) == 3:
            masks = masks.unsqueeze(1)

        imgs = imgs.to(device)
        masks = masks.float().to(device)

        optimizer.zero_grad()

        preds = model_linknet(imgs)

        loss = criterion(preds.squeeze(1), masks.squeeze(1)) + dice_loss(preds, masks)

        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        train_pbar.set_postfix(loss=loss.item())

    epoch_loss = running_loss / len(train_loader)
    linknet_train_losses.append(epoch_loss)

    print(f"Epoch {epoch+1}/{num_epochs} Loss: {epoch_loss:.4f}")

print("Training complete")

# Define validation dataset and DataLoader
val_ann_file = "/content/coco2017/annotations/instances_val2017.json"
val_img_dir = "/content/coco2017/val2017"

coco2017_val = COCO(val_ann_file)
val_ids = list(coco2017_val.imgs.keys())

val_transform = A.Compose([
    A.Resize(256, 256),
    A.Normalize(mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225]),
    ToTensorV2()
])

val_ds = COCOSubjectDataset(
    coco=coco2017_val,
    img_dir=val_img_dir,
    img_ids=val_ids,
    transform=val_transform
)

val_loader = DataLoader(
    val_ds,
    batch_size=4,
    shuffle=False,
    num_workers=2,
    pin_memory=True,
    collate_fn=custom_collate_fn # Use the same collate function as for training
)

print("Validation pipeline ready")
print("Total validation samples:", len(val_ds))

from segmentation_models_pytorch import DeepLabV3Plus

# LIMIT DATASET (correct place)
train_ds = torch.utils.data.Subset(train_ds, range(100))
train_loader = DataLoader(train_ds, batch_size=4, shuffle=True, num_workers=2, pin_memory=False, collate_fn=custom_collate_fn)

# Initialize model (FIX: remove sigmoid for BCEWithLogitsLoss)
model_deeplab = DeepLabV3Plus(
    encoder_name='resnet34',
    encoder_weights='imagenet',
    in_channels=3,
    classes=1,
    activation=None
)

model_deeplab.to(device)

criterion = nn.BCEWithLogitsLoss()
dice_loss = DiceLoss(mode='binary')
optimizer = optim.Adam(model_deeplab.parameters(), lr=1e-4)
iou_metric = JaccardIndex(task='binary').to(device)

num_epochs = 5
deeplab_train_losses, deeplab_val_ious = [], []

for epoch in range(num_epochs):
    model_deeplab.train()
    running_loss = 0.0

    train_pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}", total=len(train_loader))

    for imgs, masks in train_pbar:
        imgs, masks = imgs.to(device), masks.float().to(device)

        optimizer.zero_grad()
        preds = model_deeplab(imgs)

        loss = criterion(preds.squeeze(1), masks.squeeze(1)) + dice_loss(preds, masks)

        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        train_pbar.set_postfix(loss=loss.item())

    epoch_loss = running_loss / len(train_loader)
    deeplab_train_losses.append(epoch_loss)

    print(f"Epoch {epoch+1}/{num_epochs} Loss: {epoch_loss:.4f}")

print("Training complete")

from segmentation_models_pytorch import Unet

# Re-limit dataset to 100 samples for consistency, if not already done by a previous cell
train_ds_unet = torch.utils.data.Subset(train_ds, range(100))
train_loader_unet = DataLoader(train_ds_unet, batch_size=4, shuffle=True, num_workers=2, pin_memory=False, collate_fn=custom_collate_fn)

# Initialize U-Net model
model = Unet(
    encoder_name='resnet34',
    encoder_weights='imagenet',
    in_channels=3,
    classes=1,
    activation=None # Use None for BCEWithLogitsLoss
)

model.to(device)

# Define loss, optimizer, and metric specifically for U-Net
criterion_unet = nn.BCEWithLogitsLoss()
dice_loss_unet = DiceLoss(mode='binary')
optimizer_unet = optim.Adam(model.parameters(), lr=1e-4)
iou_metric_unet = JaccardIndex(task='binary').to(device)

num_epochs_unet = 5
unet_train_losses = []

print("Starting U-Net Training...")
for epoch in range(num_epochs_unet):
    model.train()
    running_loss = 0.0

    train_pbar_unet = tqdm(train_loader_unet, desc=f"U-Net Epoch {epoch+1}", total=len(train_loader_unet))

    for imgs, masks in train_pbar_unet:
        imgs, masks = imgs.to(device), masks.float().to(device)

        optimizer_unet.zero_grad()
        preds = model(imgs)

        loss = criterion_unet(preds.squeeze(1), masks.squeeze(1)) + dice_loss_unet(preds, masks)

        loss.backward()
        optimizer_unet.step()

        running_loss += loss.item()
        train_pbar_unet.set_postfix(loss=loss.item())

    epoch_loss = running_loss / len(train_loader_unet)
    unet_train_losses.append(epoch_loss)

    print(f"U-Net Epoch {epoch+1}/{num_epochs_unet} Loss: {epoch_loss:.4f}")

print("U-Net Training complete")

import torchmetrics.functional as F
import pandas as pd

# 1. Set all models to evaluation mode
model.eval()
model_linknet.eval()
model_deeplab.eval()

# Initialize metric accumulators
metrics = {
    'U-Net': {'iou': 0.0, 'dice': 0.0},
    'LinkNet': {'iou': 0.0, 'dice': 0.0},
    'DeepLabV3+': {'iou': 0.0, 'dice': 0.0}
}

# 2 & 3. Iterate through val_loader
val_loader = DataLoader(torch.utils.data.Subset(val_loader.dataset, range(50)), batch_size=4)
with torch.no_grad():
    for imgs, masks in tqdm(val_loader, desc="Evaluating models"):
        imgs, masks = imgs.to(device), masks.float().to(device)
        target = masks.squeeze(1).long()

        # U-Net predictions
        preds_unet = model(imgs).squeeze(1)
        bin_unet = (preds_unet > 0.5).long()
        metrics['U-Net']['iou'] += iou_metric(bin_unet, target).item()
        metrics['U-Net']['dice'] += F.f1_score(bin_unet, target, task='binary').item()

        # LinkNet predictions
        preds_link = model_linknet(imgs).squeeze(1)
        bin_link = (preds_link > 0.5).long()
        metrics['LinkNet']['iou'] += iou_metric(bin_link, target).item()
        metrics['LinkNet']['dice'] += F.f1_score(bin_link, target, task='binary').item()

        # DeepLabV3+ predictions
        preds_deep = model_deeplab(imgs).squeeze(1)
        bin_deep = (preds_deep > 0.5).long()
        metrics['DeepLabV3+']['iou'] += iou_metric(bin_deep, target).item()
        metrics['DeepLabV3+']['dice'] += F.f1_score(bin_deep, target, task='binary').item()

# 6. Calculate Mean Scores
num_batches = len(val_loader)
final_results = []
for arch, m in metrics.items():
    final_results.append({
        'Architecture': arch,
        'Mean IoU': m['iou'] / num_batches,
        'Mean Dice': m['dice'] / num_batches
    })

# 7. Print summary table
results_df = pd.DataFrame(final_results)
print("\nQuantitative Evaluation Results:")
print(results_df.to_string(index=False))

#Visual Comparison
import random
import matplotlib.pyplot as plt
import torch

# Define the denormalization function
def denorm(tensor):
    mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
    std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)
    return tensor * std + mean

# 1. Set all models to evaluation mode
model.eval()
model_linknet.eval()
model_deeplab.eval()

# 2. Select 3 random samples from val_ds
sample_indices = random.sample(range(len(val_ds)), 3)
fig, axs = plt.subplots(3, 5, figsize=(20, 12))

with torch.no_grad():
    for i, idx in enumerate(sample_indices):
        img_tensor, gt_mask = val_ds[idx]
        input_tensor = img_tensor.unsqueeze(0).to(device)

        # 3b. Pass through models
        pred_unet = (model(input_tensor) > 0.5).float().squeeze().cpu().numpy()
        pred_link = (model_linknet(input_tensor) > 0.5).float().squeeze().cpu().numpy()
        pred_deep = (model_deeplab(input_tensor) > 0.5).float().squeeze().cpu().numpy()

        # 3d. Denormalize image for visualization
        vis_img = denorm(img_tensor).permute(1, 2, 0).numpy().clip(0, 1)

        # 5 & 6. Plotting
        axs[i, 0].imshow(vis_img)
        axs[i, 0].set_title("Input")

        axs[i, 1].imshow(gt_mask.squeeze().numpy(), cmap='gray')
        axs[i, 1].set_title("GT Mask")

        axs[i, 2].imshow(pred_unet, cmap='gray')
        axs[i, 2].set_title("U-Net")

        axs[i, 3].imshow(pred_link, cmap='gray')
        axs[i, 3].set_title("LinkNet")

        axs[i, 4].imshow(pred_deep, cmap='gray')
        axs[i, 4].set_title("DeepLabV3+")

        for ax in axs[i]:
            ax.axis('off')

plt.tight_layout()
plt.show()

import cv2
import numpy as np
import torch

# 1. Best model selection (DeepLabV3+ often performs well, but we use the general 'model_deeplab' here)
best_model = model_deeplab
best_model.eval()

# 2. Define kernel for morphological operations
kernel = np.ones((5, 5), np.uint8)

# 3. Select a sample from validation set
img_tensor, gt_mask = val_ds[random.choice(range(len(val_ds)))]
input_tensor = img_tensor.unsqueeze(0).to(device)

with torch.no_grad():
    pred = best_model(input_tensor)
    pred_mask = (pred > 0.5).float().squeeze().cpu().numpy().astype(np.uint8)

# 4. Apply Morphological Opening (remove noise)
refined_mask = cv2.morphologyEx(pred_mask, cv2.MORPH_OPEN, kernel)

# 5. Apply Morphological Closing (fill holes)
refined_mask = cv2.morphologyEx(refined_mask, cv2.MORPH_CLOSE, kernel)

# 6. Visualization
vis_img = denorm(img_tensor).permute(1, 2, 0).numpy().clip(0, 1)

fig, axs = plt.subplots(1, 4, figsize=(20, 5))
axs[0].imshow(vis_img)
axs[0].set_title("Original Image")

axs[1].imshow(pred_mask, cmap='gray')
axs[1].set_title("Raw Predicted Mask")

axs[2].imshow(refined_mask, cmap='gray')
axs[2].set_title("Refined Mask (Morphology)")

overlay = vis_img.copy()
overlay[refined_mask == 1] = overlay[refined_mask == 1] * 0.5 + np.array([1, 0, 0]) * 0.5
axs[3].imshow(overlay)
axs[3].set_title("Refined Overlay")

for ax in axs:
    ax.axis('off')

plt.tight_layout()
plt.show()

print("Morphological post-processing applied: Opening (5x5) and Closing (5x5).")

import torch

# Save the U-Net model
torch.save(model.state_dict(), 'best_unet_model.pth')

print("U-Net model saved successfully as 'best_unet_model.pth'.")

#Loading best model for Inference
import torch
from segmentation_models_pytorch import Unet

# 1. Initialize the U-Net model with the same architecture as saved
model = Unet(encoder_name='resnet34', encoder_weights='imagenet', in_channels=3, classes=1, activation='sigmoid')

# Move model to the correct device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)

# 2. Load the saved model weights
model.load_state_dict(torch.load('best_unet_model.pth', map_location=device))

# 3. Set the loaded model to evaluation mode
model.eval()

print("U-Net model loaded successfully and set to evaluation mode.")

import cv2
import torch
import numpy as np

def predict_and_refine(image_path, model, val_transform, device, denorm_fn, kernel):
    # 1. Load the image
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # 2. Apply validation transform
    transformed = val_transform(image=image)
    input_tensor = transformed['image'].unsqueeze(0).to(device)

    # 3. Perform inference
    model.eval()
    with torch.no_grad():
        raw_prediction = model(input_tensor)

    # 4. Threshold predictions to get binary mask
    predicted_mask = (raw_prediction > 0.5).float().squeeze().cpu().numpy().astype(np.uint8)

    # 5. Apply morphological opening and closing
    refined_mask = cv2.morphologyEx(predicted_mask, cv2.MORPH_OPEN, kernel)
    refined_mask = cv2.morphologyEx(refined_mask, cv2.MORPH_CLOSE, kernel)

    # 6. Denormalize original image for visualization
    original_image_display = denorm_fn(input_tensor.squeeze(0)).permute(1, 2, 0).cpu().numpy().clip(0, 1)

    return original_image_display, predicted_mask, refined_mask

print("Defined 'predict_and_refine' function for inference and post-processing.")

import os
import matplotlib.pyplot as plt
import cv2
import numpy as np

# 1. Define a list of image paths (using existing images from the dataset for demonstration)
sample_image_filenames = [
    "000000000009.jpg",
    "000000000025.jpg",
    "000000000034.jpg"
]
sample_image_paths = [os.path.join(train_img_dir, fn) for fn in sample_image_filenames]

# 2. Create a directory named 'isolated_subjects' to save the output images
output_dir = 'isolated_subjects'
os.makedirs(output_dir, exist_ok=True)
print(f"Output directory '{output_dir}' created or already exists.")

# Define denorm_fn and kernel, as they are required by predict_and_refine function
def denorm(img_tensor):
    mean = torch.tensor([0.485, 0.456, 0.406]).view(3,1,1).to(img_tensor.device)
    std = torch.tensor([0.229, 0.224, 0.225]).view(3,1,1).to(img_tensor.device)
    return img_tensor * std + mean

kernel = np.ones((5, 5), np.uint8)

# Define val_transform (assuming it's already defined from previous steps)
# If not, it should be defined here:
val_transform = A.Compose([
    A.Resize(256, 256),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2()
])

# 3. Iterate through the list of sample image paths
for i, image_path in enumerate(sample_image_paths):
    print(f"Processing image: {os.path.basename(image_path)}")
    original_image_display, predicted_mask, refined_mask = predict_and_refine(
        image_path, model, val_transform, device, denorm, kernel
    )

    # b. Create a figure with subplots
    fig, axs = plt.subplots(1, 4, figsize=(20, 5))

    axs[0].imshow(original_image_display)
    axs[0].set_title("Original Image")
    axs[0].axis('off')

    axs[1].imshow(predicted_mask, cmap='gray')
    axs[1].set_title("Raw Predicted Mask")
    axs[1].axis('off')

    axs[2].imshow(refined_mask, cmap='gray')
    axs[2].set_title("Refined Mask")
    axs[2].axis('off')

    # c. For the subject-isolated overlay
    isolated_overlay = original_image_display.copy()
    # Set pixels where the refined mask is 0 to black
    isolated_overlay[refined_mask == 0] = 0

    # d. Display the plots
    axs[3].imshow(isolated_overlay)
    axs[3].set_title("Subject Isolated Overlay")
    axs[3].axis('off')

    plt.tight_layout()
    plt.show()

    # e. Save the subject-isolated overlay image
    output_filename = os.path.join(output_dir, f"isolated_{os.path.basename(image_path)}")
    # Convert float image (0-1) to uint8 (0-255) for saving with OpenCV, or use plt.imsave
    plt.imsave(output_filename, isolated_overlay)
    print(f"Saved isolated subject to {output_filename}")

print("Inference and visualization for sample images complete.")

from google.colab import files

# 1. Upload a custom image file
print("Please upload a custom image file (JPG or PNG).")
uploaded_file = files.upload()

# 2. Retrieve the filename of the uploaded image
if uploaded_file:
    custom_image_path = list(uploaded_file.keys())[0]
    print(f"File '{custom_image_path}' uploaded successfully.")
else:
    custom_image_path = None
    print("No file was uploaded.")

import matplotlib.pyplot as plt
import os

# Ensure the uploaded file path exists
if custom_image_path and os.path.exists(custom_image_path):
    print(f"Processing custom image: {custom_image_path}")

    # Perform inference and refinement using the custom image
    original_image_display, predicted_mask, refined_mask = predict_and_refine(
        custom_image_path, model, val_transform, device, denorm, kernel
    )

    # Visualization
    fig, axs = plt.subplots(1, 4, figsize=(20, 5))

    axs[0].imshow(original_image_display)
    axs[0].set_title("Original Custom Image")
    axs[0].axis('off')

    axs[1].imshow(predicted_mask, cmap='gray')
    axs[1].set_title("Raw Predicted Mask")
    axs[1].axis('off')

    axs[2].imshow(refined_mask, cmap='gray')
    axs[2].set_title("Refined Mask")
    axs[2].axis('off')

    # Subject-isolated overlay
    isolated_overlay = original_image_display.copy()
    isolated_overlay[refined_mask == 0] = 0

    axs[3].imshow(isolated_overlay)
    axs[3].set_title("Subject Isolated Overlay")
    axs[3].axis('off')

    plt.tight_layout()
    plt.show()

    # Optionally save the isolated image
    output_dir = 'isolated_subjects_custom'
    os.makedirs(output_dir, exist_ok=True)
    output_filename = os.path.join(output_dir, f"isolated_custom_{os.path.basename(custom_image_path)}")
    plt.imsave(output_filename, isolated_overlay)
    print(f"Saved isolated custom image to {output_filename}")

else:
    print("No custom image path available or file does not exist. Please upload an image first.")